version: "3"

services:
  database:
    container_name: mysql-container
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: showmethemoney
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: "Asia/Seoul"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./src/main/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  application:
    container_name: spring-boot-container
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
